import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { TrackerContext } from "../vendors";
import React from "react";

const Home: NextPage = () => {
  const { initTracker, startTracking, profiler, logIssue } =
    React.useContext(TrackerContext);

  React.useEffect(() => {
    initTracker();
    startTracking();
  }, []);

  // const handleClick = profiler("MyFunction")(() => {
  //   logIssue({
  //     name: "Click button",
  //     data: {
  //       purpose: "test profiler",
  //     },
  //   });
  // });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <button onClick={handleClick}>Click here</button> */}
    </div>
  );
};

export default Home;
