import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { TrackerContext } from "../vendors";
import React from "react";
import Image from "next/image";

const Home: NextPage = () => {
  const { initTracker, startTracking, reportError } =
    React.useContext(TrackerContext);

  console.log(process.env.NODE_ENV);

  React.useEffect(() => {
    if (process.env.NODE_ENV === "production") {
      initTracker();
      startTracking();
    }
  }, []);

  const handleClick = async () => {
    try {
      const response = await fetch("abcxsxd");
      throw new Error();
    } catch (error) {
      reportError(error as Error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={handleClick}>Ceecek here</button>

      <Image
        className="abc"
        src="/images/tree.jpg"
        height="350px"
        width="350px"
        layout="fill"
      />
    </div>
  );
};

export default Home;
